export default {
	'blockypage-blocks/text': [ 'text' ],
	'blockypage-blocks/team': [ 'name', 'role', 'description', 'image' ],
	'blockypage-blocks/pricing': [
		'title',
		'subtitle',
		'price',
		'currency',
		'per',
		'footerOptionTxt',
		'iconsList',
	],
	'blockypage-blocks/infobox': [ 'title', 'information', 'image' ],
	'blockypage-blocks/button': [ 'url', 'text' ],
	'blockypage-blocks/calltoaction': [ 'image', 'title', 'text' ],
	'blockypage-blocks/container': [],
	'blockypage-blocks/heading': [ 'text' ],
	'blockypage-blocks/divider': [],
	'blockypage-blocks/counter': [ 'number', 'text', 'sign' ],
	'blockypage-blocks/iconbox': [ 'iconBox_icon' ],
	'blockypage-blocks/iconlist': [ 'iconsList' ],
	'blockypage-blocks/image': [
		'imageBlockUr',
		'imageBlockCaption',
		'imageBlockAlt',
	],
	'blockypage-blocks/spacer': [],
	'blockypage-blocks/tabs': [ 'tabs' ],
	'blockypage-blocks/testimonial': [
		'topIcon',
		'bottomIcon',
		'message',
		'avatar',
		'name',
		'job',
	],
	'blockypage-blocks/videopopup': [],
	'blockypage-blocks/accordion': [],
	'blockypage-blocks/accordion-item': [ 'title', 'icon' ],
};
